/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-08-05 03:30:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.phone;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/phone/inc/foot_inc.jsp", Long.valueOf(1375668141703L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html><html><head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>会员登录 </title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"yes\" name=\"apple-mobile-web-app-capable\">\r\n");
      out.write("<meta content=\"black\" name=\"apple-mobile-web-app-status-bar-style\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/phone/css/1379217.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/phone/css/16251628.css\">\r\n");
      out.write("<link><script type=\"text/javascript\" async=\"\" id=\"tb-beacon-aplus\" exparams=\"req_url=http%3a%2f%2flogin%2em%2etaobao%2ecom%2flogin%2ehtm%3fttid%3deguc01%26sid%3d6a94650e8527c1c2%26tpl%5fredirect%5furl%3dhttp%253A%252F%252Fcaipiao%2em%2etaobao%2ecom%252Flottery%252Fwap%252Findex%2ehtm%253Fsid%253D6a94650e8527c1c2%2526ttid%253Deguc01%2526spm%253D41%2e351606%2e292993%2e8%2526sprefer%253Dp23597%26lsid%3dd3610ffa8e657d2d719f&amp;amp;cna=V7pbCmI92yACAQEAAH8kReXV&amp;amp;category=&amp;amp;pre=http%3a%2f%2fcaipiao%2em%2etaobao%2ecom%2f%3fsid%3d6a94650e8527c1c2%26ttid%3deguc01%26spm%3d41%2e351606%2e292993%2e8%26sprefer%3dp23597&amp;amp;userid=&amp;amp;b2c_orid=&amp;amp;b2c_auction=&amp;amp;at_isb=atp_isdpp=&amp;amp;at_ssid=&amp;amp;aplus&amp;amp;at_cart=&amp;amp;at_alitrackid=&amp;amp;at_udid=&amp;amp;sc=&amp;amp;wp=aXBob25l&amp;amp;sell=&amp;amp;TBTrack_Id=du%3d6a94650e8527c1c2\" src=\"/phone/js/8989722.js\"></script></head>\r\n");
      out.write("<body scroll=\"none\"><script type=\"text/javascript\">\r\n");
      out.write("(function (d) {\r\n");
      out.write("var t=d.createElement(\"script\");t.type=\"text/javascript\";t.async=true;t.id=\"tb-beacon-aplus\";\r\n");
      out.write("t.setAttribute(\"exparams\",\"req_url=http%3a%2f%2flogin%2em%2etaobao%2ecom%2flogin%2ehtm%3fttid%3deguc01%26sid%3d6a94650e8527c1c2%26tpl%5fredirect%5furl%3dhttp%253A%252F%252Fcaipiao%2em%2etaobao%2ecom%252Flottery%252Fwap%252Findex%2ehtm%253Fsid%253D6a94650e8527c1c2%2526ttid%253Deguc01%2526spm%253D41%2e351606%2e292993%2e8%2526sprefer%253Dp23597%26lsid%3dd3610ffa8e657d2d719f&amp;cna=V7pbCmI92yACAQEAAH8kReXV&amp;category=&amp;pre=http%3a%2f%2fcaipiao%2em%2etaobao%2ecom%2f%3fsid%3d6a94650e8527c1c2%26ttid%3deguc01%26spm%3d41%2e351606%2e292993%2e8%26sprefer%3dp23597&amp;userid=&amp;b2c_orid=&amp;b2c_auction=&amp;at_isb=atp_isdpp=&amp;at_ssid=&amp;aplus&amp;at_cart=&amp;at_alitrackid=&amp;at_udid=&amp;sc=&amp;wp=aXBob25l&amp;sell=&amp;TBTrack_Id=du%3d6a94650e8527c1c2\");\r\n");
      out.write("if(\"https:\"==d.location.protocol){t.src=\"https://s.tbcdn.cn/s/aplus_wap.js\";}else{t.src=\"http://a.tbcdn.cn/s/aplus_wap.js\";}\r\n");
      out.write("d.getElementsByTagName(\"head\")[0].appendChild(t);\r\n");
      out.write("})(document);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkForm(){\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar loginName=$.trim($(\"#loginName\").val());\r\n");
      out.write("\tvar password=$.trim($(\"#password\").val());\r\n");
      out.write("\tif(loginName.length<1){\r\n");
      out.write("\t\t$(\"#ts\").html(\"用户名不能为空\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(loginName.length>50){\r\n");
      out.write("\t\t$(\"#ts\").html(\"用户名过长\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(loginName.length<6){\r\n");
      out.write("\t\t$(\"#ts\").html(\"用户名不得小于6位\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(password.length<1){\r\n");
      out.write("\t\t$(\"#ts\").html(\"密码不能为空\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(password.length>50){\r\n");
      out.write("\t\t$(\"#ts\").html(\"密码过长\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(password.length<6){\r\n");
      out.write("\t\t$(\"#ts\").html(\"密码不得小于6位\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   async : false,\r\n");
      out.write("\t\t\t   cache : false,\r\n");
      out.write("\t\t\t   type: \"GET\",\r\n");
      out.write("\t\t\t   url: \"/phone/user/login.do?loginName=\"+loginName+\"&password=\"+password,\r\n");
      out.write("\t\t\t   dataType:\"text\",\r\n");
      out.write("\t\t\t   success: function(msg){\t\t\t\t  \r\n");
      out.write("\t\t\t     if(msg=='success'){\t\t\t    \t\t    \r\n");
      out.write("\t\t\t    \twindow.location.href='/phone/index.jsp';\r\n");
      out.write("\t\t\t     }else if(msg=='fail'){\t\r\n");
      out.write("\t\t\t    \t $(\"#ts\").html(\"登录超时！\");\r\n");
      out.write("\t\t\t     }else if(msg=='loginNameIsNull'){\t\r\n");
      out.write("\t\t\t    \t $(\"#ts\").html(\"用户名不能为空！\");\r\n");
      out.write("\t\t\t     }else if(msg=='passfail'){\r\n");
      out.write("\t\t\t    \t $(\"#ts\").html(\"用户名或者密码不正确！\");\r\n");
      out.write("\t\t\t     }\t\t     \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"tbh5v0\">\r\n");
      out.write("<div class=\"screen-wrap fullscreen login\">\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("<div class=\"c-inav\">\r\n");
      out.write("<section>\r\n");
      out.write("\r\n");
      out.write("<button class=\"back\">\r\n");
      out.write("<span><em></em></span><a href=\"/phone/index.jsp\">首页</a>\r\n");
      out.write("                    </button>\r\n");
      out.write("</section>\r\n");
      out.write("<section>\r\n");
      out.write("<span>会员登录</span>\r\n");
      out.write("</section>\r\n");
      out.write("<section></section>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("<section class=\"innercontent\">\r\n");
      out.write("       <form class=\"c-form login-form\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("                    <div class=\"field username\">\r\n");
      out.write("                        <div class=\"c-form-search\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"loginName\" id=\"loginName\" placeholder=\"手机号/会员名\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                   \t</div>\r\n");
      out.write("                    <div class=\"field pwd\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"密码\" class=\"c-form-txt-normal\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <font id=\"ts\" color=\"red\"></font>\r\n");
      out.write("                    <div class=\"field submit-btn\">\r\n");
      out.write("                        <input type=\"button\" class=\"c-btn-oran-big\" value=\"登 录\" onclick=\"checkForm()\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    </form>                                                                        </fieldset>\r\n");
      out.write("           \r\n");
      out.write("       </section>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/phone/js/5800517.js\"></script>\r\n");
      out.write("<script src=\"/phone/js/1457736.js\"></script>        \r\n");
      out.write("<script src=\"/phone/js/4824878.js\"></script>\r\n");
      out.write("<script src=\"/phone/js/6867676.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("try{\r\n");
      out.write("if(getSpecificCookie('new_wud') != 'wud67200'){\r\n");
      out.write("document.getElementById('cookie-support-div').style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("}catch(e){// 有异常时不做任何处理\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        var Login = new Login();\r\n");
      out.write("        Login.loginForm();\r\n");
      out.write("\r\n");
      out.write("    //设置nickValue\r\n");
      out.write("if(window.localStorage && document.getElementById('J_UserNameTxt').value =='')\r\n");
      out.write("{\r\n");
      out.write(" document.getElementById('J_UserNameTxt').value = window.localStorage.getItem('lastNick');\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("    /*\r\n");
      out.write("         * 读取特定Cookie的通用函数\r\n");
      out.write("         */\r\n");
      out.write("        function getSpecificCookie(name) {\r\n");
      out.write("              if(document.cookie.length > 0) {\r\n");
      out.write("                    start = document.cookie.indexOf(name + \"=\");\r\n");
      out.write("                    if( start != -1) {\r\n");
      out.write("                          start = start + name.length + 1;\r\n");
      out.write("                          end = document.cookie.indexOf(\";\",start);\r\n");
      out.write("                          if( end == -1) {\r\n");
      out.write("                                end = document.cookie.length;\r\n");
      out.write("                          }\r\n");
      out.write("                    }\r\n");
      out.write("                    return decodeURI(document.cookie.substring(start,end));\r\n");
      out.write("              }\r\n");
      out.write("              return \"\";\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                 <footer class=\"footer c-footer \">\r\n");
      out.write("            <section class=\"footer-t c-footer-t\">\r\n");
      out.write("                  <p class=\"user-info c-user-info\">\r\n");
      out.write("                                               <span><a id=\"J_footer_login\" href=\"/phone/login.jsp\">登录</a></span><span><a href=\"/phone/register.jsp\">注册</a></span>\r\n");
      out.write("                                           </p>\r\n");
      out.write("                  <p class=\"gotop c-gotop\"><a id=\"J_GoTop\" href=\"javascript:scroll(0,0)\">top<b> </b></a></p>\r\n");
      out.write("               </section>\r\n");
      out.write("               <br>\r\n");
      out.write("               <br>\r\n");
      out.write("               <br>\r\n");
      out.write("               ");
      out.write('\r');
      out.write('\n');
      out.write("<p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tCopyright 2013<br>\r\n");
      out.write("\t\t\t\t<a href=\"http://www.doqian.com/\">广州度阡信息科技有限公司</a>\r\n");
      out.write("\t\t\t</p>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<script src=\"/phone/js/7108814.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("window.addEventListener('load', function(){\r\n");
      out.write("//set webp\r\n");
      out.write("MH5.webp.detectAndSetCookie();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<input type=\"hidden\" id=\"J_app_key\" value=\"12574478\">        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
