/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-08-08 06:04:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.sysadm.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class editFavourableActivityUI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/doqian.tld", Long.valueOf(1375668126859L));
    _jspx_dependants.put("/includes/page_inc.jsp", Long.valueOf(1375668129343L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <title>品牌编辑</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sysadm/css/base.css\"></link>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"/js/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t//保证用户输入跟黏贴数据只能是数字跟小数点\r\n");
      out.write("\t$(\"#minAmount\").keyup(function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t\t$(this).val(tmptxt.replace(/[^\\d.]/g, ''));\r\n");
      out.write("\r\n");
      out.write("\t\t}).bind(\"paste\", function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t$(this).val(tmptxt.replace(/\\D|^0/g, ''));\r\n");
      out.write("\t}).css(\"ime-mode\", \"disabled\");\r\n");
      out.write("\t$(\"#maxAmount\").keyup(function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t\t$(this).val(tmptxt.replace(/[^\\d.]/g, ''));\r\n");
      out.write("\r\n");
      out.write("\t\t}).bind(\"paste\", function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t$(this).val(tmptxt.replace(/\\D|^0/g, ''));\r\n");
      out.write("\t}).css(\"ime-mode\", \"disabled\");\r\n");
      out.write("\t$(\"#actTypeExt\").keyup(function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t\t$(this).val(tmptxt.replace(/[^\\d.]/g, ''));\r\n");
      out.write("\r\n");
      out.write("\t\t}).bind(\"paste\", function() {\r\n");
      out.write("\t\tvar tmptxt = $(this).val();\r\n");
      out.write("\t\t$(this).val(tmptxt.replace(/\\D|^0/g, ''));\r\n");
      out.write("\t}).css(\"ime-mode\", \"disabled\");\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\tif($(\"#actRange\").val() != 0){\r\n");
      out.write("\t\t$(\"#youhuiTr\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar gprotime = $(\"#startTime\").val();\r\n");
      out.write("\tif ($(\"#startTime\").val() == \"\") {\r\n");
      out.write("\t\treturn (false);\r\n");
      out.write("\t}\r\n");
      out.write("\tvar gprotime = parseInt(gprotime)\r\n");
      out.write("\tvar newTime = new Date(gprotime); //就得到普通的时间了\r\n");
      out.write("\tvar momth = newTime.getMonth() + 1;\r\n");
      out.write("\t$(\"#startTime\").val(\r\n");
      out.write("\t\t\tnewTime.getFullYear() + \"-\" + momth + \"-\" + newTime.getDate()\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\tvar gprotime = $(\"#endTime\").val();\r\n");
      out.write("\tif ($(\"#endTime\").val() == \"\") {\r\n");
      out.write("\t\treturn (false);\r\n");
      out.write("\t}\r\n");
      out.write("\tvar gprotime = parseInt(gprotime)\r\n");
      out.write("\tvar newTime = new Date(gprotime); //就得到普通的时间了\r\n");
      out.write("\tvar momth = newTime.getMonth() + 1;\r\n");
      out.write("\t$(\"#endTime\").val(\r\n");
      out.write("\t\t\tnewTime.getFullYear() + \"-\" + momth + \"-\" + newTime.getDate()\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkForm(){\r\n");
      out.write("\tvar actName = $(\"#actName\").val();\r\n");
      out.write("\tvar minAmount = $(\"#minAmount\").val();\r\n");
      out.write("\tvar maxAmount = $(\"#maxAmount\").val();\r\n");
      out.write("\tif($.trim(actName) == \"\"){\r\n");
      out.write("\t\talert(\"优惠活动名称必填\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($.trim(minAmount) == \"\"){\r\n");
      out.write("\t\talert(\"优惠活动金额下限必填\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($.trim(maxAmount) == \"\"){\r\n");
      out.write("\t\talert(\"优惠活动金额上限必填\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif ($(\"#startTime\").val().length > 0 || $(\"#startTime\").val() != \"\") {\r\n");
      out.write("\t\tvar gprotime = $(\"#startTime\").val();\r\n");
      out.write("\t\tvar formated_time = gprotime.replace(\"-\", \"/\");\r\n");
      out.write("\t\tvar formated_time = formated_time.replace(\"-\", \"/\");\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar oldTime = (new Date(formated_time)).getTime(); //得到毫秒数 \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#startTime\").val(oldTime);\r\n");
      out.write("\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"开始时间不能为空 ！！！\");\r\n");
      out.write("\t\t$(\"#startTime\").val(\"\")\r\n");
      out.write("\t\t$(\"#endTime\").val(\"\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif ($(\"#endTime\").val().length > 0 || $(\"#endTime\").val() != \"\") {\r\n");
      out.write("\t\tvar gprotime = $(\"#endTime\").val();\r\n");
      out.write("\t\tvar formated_time = gprotime.replace(\"-\", \"/\");\r\n");
      out.write("\t\tvar formated_time = formated_time.replace(\"-\", \"/\");\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar oldTime = (new Date(formated_time)).getTime(); //得到毫秒数 \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#endTime\").val(oldTime);\r\n");
      out.write("\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"结束时间不能为空 ！！！\");\r\n");
      out.write("\t\t$(\"#startTime\").val(\"\")\r\n");
      out.write("\t\t$(\"#endTime\").val(\"\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function help(objId){\r\n");
      out.write("\t$(\"#\"+objId).toggle();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeyouhui(obj){\r\n");
      out.write("\t$(\"#youhuiGoods\").empty();\r\n");
      out.write("\t$(\"#items\").empty();\r\n");
      out.write("\t$(\"#jia\").hide();\r\n");
      out.write("\tvar youhuiVal = $(obj).val();\r\n");
      out.write("\tif(youhuiVal != 0){\r\n");
      out.write("\t\t$(\"#youhuiTr\").show();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#youhuiTr\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function seaechHandle(){\r\n");
      out.write("\tif($(\"#actRange\").val() == 3){\r\n");
      out.write("\t\t//搜索商品\r\n");
      out.write("\t\tseaechGoods();\r\n");
      out.write("\t}else if($(\"#actRange\").val() == 2){\r\n");
      out.write("\t\t//搜索品牌\r\n");
      out.write("\t\tseaechBrand();\r\n");
      out.write("\t}else if($(\"#actRange\").val() == 1){\r\n");
      out.write("\t\t//搜索分类\r\n");
      out.write("\t\tseaechCategory();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//搜索商品\r\n");
      out.write("function seaechGoods(){\r\n");
      out.write("\tvar keyGoodsName = $(\"#keyGoodsName\").val();\r\n");
      out.write("\tkeyGoodsName = encodeURI($.trim(keyGoodsName));\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tcache : false,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\turl:\"/sysadm/favourableActivity/getGoodsByKeySearch.do?key=\"+keyGoodsName,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$(\"#youhuiGoods\").empty();\r\n");
      out.write("\t\t\tvar size = data.length;\r\n");
      out.write("\t\t\t//迭代\r\n");
      out.write("\t\t\tfor(var i=0;i<size;i++){\r\n");
      out.write("\t\t\t\tvar goodsOption = $(\"<option value='\"+data[i].goodsId+\"'>\"+data[i].goodsName+\"</option>\");\r\n");
      out.write("\t\t\t\t$(\"#youhuiGoods\").append(goodsOption);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(size > 0){\r\n");
      out.write("\t\t\t\t$(\"#jia\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("//搜索品牌\r\n");
      out.write("function seaechBrand(){\r\n");
      out.write("\tvar keyGoodsName = $(\"#keyGoodsName\").val();\r\n");
      out.write("\tkeyGoodsName = encodeURI($.trim(keyGoodsName));\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tcache : false,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\turl:\"/sysadm/favourableActivity/getBrandByKeySearch.do?key=\"+keyGoodsName,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$(\"#youhuiGoods\").empty();\r\n");
      out.write("\t\t\tvar size = data.length;\r\n");
      out.write("\t\t\t//迭代\r\n");
      out.write("\t\t\tfor(var i=0;i<size;i++){\r\n");
      out.write("\t\t\t\tvar goodsOption = $(\"<option value='\"+data[i].brandId+\"'>\"+data[i].brandName+\"</option>\");\r\n");
      out.write("\t\t\t\t$(\"#youhuiGoods\").append(goodsOption);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(size > 0){\r\n");
      out.write("\t\t\t\t$(\"#jia\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("//搜索分类\r\n");
      out.write("function seaechCategory(){\r\n");
      out.write("\tvar keyGoodsName = $(\"#keyGoodsName\").val();\r\n");
      out.write("\tkeyGoodsName = encodeURI($.trim(keyGoodsName));\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tcache : false,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\turl:\"/sysadm/favourableActivity/getCategoryByKeySearch.do?key=\"+keyGoodsName,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$(\"#youhuiGoods\").empty();\r\n");
      out.write("\t\t\tvar size = data.length;\r\n");
      out.write("\t\t\t//迭代\r\n");
      out.write("\t\t\tfor(var i=0;i<size;i++){\r\n");
      out.write("\t\t\t\tvar goodsOption = $(\"<option value='\"+data[i].catId+\"'>\"+data[i].catName+\"</option>\");\r\n");
      out.write("\t\t\t\t$(\"#youhuiGoods\").append(goodsOption);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(size > 0){\r\n");
      out.write("\t\t\t\t$(\"#jia\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function jiaHandle(){\r\n");
      out.write("\tvar tab = 0;\r\n");
      out.write("\tif($(\"#youhuiGoods\").val()){\r\n");
      out.write("\t\tvar id = $(\"#youhuiGoods\").val();\r\n");
      out.write("\t\t$(\"input[name='actRangeExtIds']\").each(function(i){\r\n");
      out.write("\t\t\t   if($(this).val() == id){\r\n");
      out.write("\t\t\t\t   tab = 1;\r\n");
      out.write("\t\t\t\t   alert(\"该选项已存在！\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\tvar name = $(\"#youhuiGoods option:selected\").text();\r\n");
      out.write("\t\tvar $input = \"<input type='checkbox' name='actRangeExtIds' value='\"+id+\"' checked='checked'/>\"+name+\"<br/>\";\r\n");
      out.write("\t\tif(tab == 0){\r\n");
      out.write("\t\t\t$(\"#items\").append($input);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeyouhui2(obj){\r\n");
      out.write("\t$(\"#giftGoods\").empty();\r\n");
      out.write("\t$(\"#items2\").empty();\r\n");
      out.write("\tif($(obj).val() != 0){\r\n");
      out.write("\t\t$(\"#giftTr\").hide();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#giftTr\").show();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function seaechHandle2(){\r\n");
      out.write("\tvar keyGoodsName = $(\"#keyGoodsName2\").val();\r\n");
      out.write("\tkeyGoodsName = encodeURI($.trim(keyGoodsName));\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tcache : false,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\turl:\"/sysadm/favourableActivity/getGoodsByKeySearch.do?key=\"+keyGoodsName,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$(\"#giftGoods\").empty();\r\n");
      out.write("\t\t\tvar size = data.length;\r\n");
      out.write("\t\t\t//迭代\r\n");
      out.write("\t\t\tfor(var i=0;i<size;i++){\r\n");
      out.write("\t\t\t\tvar goodsOption = $(\"<option value='\"+data[i].goodsId+\"' title='\"+data[i].shopPrice+\"'>\"+data[i].goodsName+\"</option>\");\r\n");
      out.write("\t\t\t\t$(\"#giftGoods\").append(goodsOption);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(size > 0){\r\n");
      out.write("\t\t\t\t$(\"#jia2\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function jiaHandle2(){\r\n");
      out.write("\tvar tab = 0;\r\n");
      out.write("\tif($(\"#giftGoods\").val()){\r\n");
      out.write("\t\tvar id = $(\"#giftGoods\").val();\r\n");
      out.write("\t\t$(\"input[name='giftIds']\").each(function(i){\r\n");
      out.write("\t\t\t   if($(this).val() == id){\r\n");
      out.write("\t\t\t\t   tab = 1;\r\n");
      out.write("\t\t\t\t   alert(\"该选项已存在！\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\tvar name = $(\"#giftGoods option:selected\").text();\r\n");
      out.write("\t\tvar price = $(\"#giftGoods option:selected\").attr(\"title\");\r\n");
      out.write("\t\tvar $input = \"<input type='checkbox' name='giftIds' value='\"+id+\"' checked='checked'/>\"+name+\"&nbsp;&nbsp;<input type='text' size='10' value='价格:￥\"+price+\"'/><br/>\";\r\n");
      out.write("\t\tif(tab == 0){\r\n");
      out.write("\t\t\t$(\"#items2\").append($input);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body leftmargin=\"8\" topmargin=\"8\" background='/sysadm/images/allbg.gif'>  \r\n");
      out.write("<form name=\"form2\" action=\"/sysadm/favourableActivity/editFavourableActivity.do\" id=\"form2\" method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return checkForm()\">\r\n");
      out.write("<input type=\"hidden\" name=\"actId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<table width=\"98%\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"#D1DDAA\" align=\"center\" style=\"margin-top:8px\">\r\n");
      out.write("\r\n");
      out.write("<tr bgcolor=\"#E7E7E7\">\r\n");
      out.write("\t<td height=\"30\" background=\"/sysadm/images/tbg.gif\">&nbsp;\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t&nbsp;\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td height=\"30\" background=\"/sysadm/images/tbg.gif\" align=\"right\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"/sysadm/favourableActivity/favourableActivityList.do\"><img src=\"/sysadm/images/add.png\" title=\"商品类型列表\"/></a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"/sysadm/favourableActivity/favourableActivityList.do\">优惠活动列表</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table style=\"margin-left: 300px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>优惠活动名称：</strong></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"actName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"actName\" size=\"50\"/><font color=\"red\">*</font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>金额下限：</strong></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"minAmount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.minAmount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"minAmount\"/><font color=\"red\">*</font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>金额上限：</strong></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"maxAmount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.maxAmount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"maxAmount\"/><font color=\"red\">*</font><br/>输入0表示没有上限</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>优惠开始时间：</strong></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"startTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.startTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"startTime\" class=\"Wdate\"  onClick=\"WdatePicker({skin:'whyGreen',dateFmt:'yyyy-MM-dd'})\" style=\"cursor: pointer;\" readonly=\"readonly\"/><font color=\"red\">*</font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>优惠结束时间：</strong></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"endTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.endTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"endTime\" class=\"Wdate\"  onClick=\"WdatePicker({skin:'whyGreen',dateFmt:'yyyy-MM-dd'})\" style=\"cursor: pointer;\" readonly=\"readonly\"/><font color=\"red\">*</font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>优惠活动标题图</strong></td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"file\" name=\"pic\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\"><strong>享受优惠的会员等级：</strong></td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"range\" value=\"0\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(favourableActivity.userRank, '0') ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("/>非会员\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"range\" value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(favourableActivity.userRank, '1') ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("/>注册用户\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"range\" value=\"2\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(favourableActivity.userRank, '2') ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write(" />vip\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"range\" value=\"3\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(favourableActivity.userRank, '3') ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write(" />钻石级\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"range\" value=\"4\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(favourableActivity.userRank, '4') ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write(" />黄金级\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\" valign=\"top\"><strong>优惠范围：</strong></td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<select name=\"actRange\" onchange=\"changeyouhui(this)\" id=\"actRange\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<div id=\"items\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr style=\"display: none;\" id=\"youhuiTr\">\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\">搜索并加入优惠范围</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"keyGoodsName\"/>&nbsp;<input type=\"button\" value=\"搜索\" onclick=\"seaechHandle()\"/>&nbsp;\r\n");
      out.write("\t\t\t<select name=\"youhuiGoods\" id=\"youhuiGoods\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t&nbsp;<input type=\"button\" value=\"+\" style=\"display: none;\" id=\"jia\" onclick=\"jiaHandle()\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\" valign=\"top\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><img src=\"/sysadm/images/untitled.png\" title=\"点击此处查看提示信息\" style=\"cursor: pointer;\" onclick=\"help('attrGroup')\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><strong>优惠方式：</strong></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<select name=\"actType\" onchange=\"changeyouhui2(this)\">\r\n");
      out.write("\t\t\t\t<option value=\"0\">享受赠品</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">现金减免</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">价格折扣</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"actTypeExt\" size=\"7\" id=\"actTypeExt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actTypeExt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<span  id=\"attrGroup\">当优惠方式为“享受赠品（特惠品）”时，请输入允许买家选择赠品（特惠品）的最大数量，数量为0表示不限数量；<br/>当优惠方式为“享受现金减免”时，请输入现金减免的金额；<br/>当优惠方式为“享受价格折扣”时，请输入折扣（1－99），如：打9折，就输入90。</span>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<div id=\"items2\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr id=\"giftTr\">\r\n");
      out.write("\t\t<td align=\"right\" height=\"30\">搜索并加入赠品（特惠品）</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"keyGoodsName2\"/>&nbsp;<input type=\"button\" value=\"搜索\" onclick=\"seaechHandle2()\"/>&nbsp;\r\n");
      out.write("\t\t\t<select name=\"giftGoods\" id=\"giftGoods\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t&nbsp;<input type=\"button\" value=\"+\" style=\"display: none;\" id=\"jia2\" onclick=\"jiaHandle2()\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\" width=\"50px;\"><input type=\"submit\" value=\"确定\"/></td>\r\n");
      out.write("\t\t<td align=\"center\" width=\"50px;\"><input type=\"button\" value=\"返回\" onclick=\"history.go(-1)\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<table width='98%'  border='0' cellpadding='1' cellspacing='1' bgcolor='#CBD8AC' align=\"center\" style=\"margin-top:8px\">\r\n");
      out.write("  <tr bgcolor='#EEF4EA'>\r\n");
      out.write("    <td background='/sysadm/images/wbg.gif' align='center'>\r\n");
      out.write("      \r\n");
      out.write("\t<font color=\"red\">*</font>号为必填项目\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(301,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty favourableActivity.actId}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t添加优惠活动 \r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t修改优惠活动 \r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(365,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actRange == 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<option value=\"0\">全部商品</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">以下分类</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"2\">以下品牌</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"3\">以下商品</option>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(371,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actRange == 2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
    if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<option value=\"0\">全部商品</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"1\">以下分类</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"2\" selected=\"selected\">以下品牌</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"3\">以下商品</option>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(377,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actRange == 3}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
    if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<option value=\"0\">全部商品</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"1\">以下分类</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"2\">以下品牌</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"3\" selected=\"selected\">以下商品</option>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<option value=\"0\" selected=\"selected\">全部商品</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"1\">以下分类</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"2\">以下品牌</option>\r\n");
        out.write("\t\t\t\t\t\t<option value=\"3\">以下商品</option>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f2.setParent(null);
    int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
    if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f4(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f5(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f4 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(395,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actRange == 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
    if (_jspx_eval_c_005fwhen_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fwhen_005f4, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f4);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(396,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/sysadm/product/editFavourableActivityUI.jsp(396,6) '${RangeExtList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${RangeExtList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(396,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("rangeExt");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<input type='checkbox' name='actRangeExtIds' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.catId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("' checked='checked'/>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.catName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("<br/>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f5 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(400,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${favourableActivity.actRange == 2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f5 = _jspx_th_c_005fwhen_005f5.doStartTag();
    if (_jspx_eval_c_005fwhen_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fwhen_005f5, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f5);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(401,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/sysadm/product/editFavourableActivityUI.jsp(401,6) '${RangeExtList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${RangeExtList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(401,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("rangeExt");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<input type='checkbox' name='actRangeExtIds' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.brandId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("' checked='checked'/>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.brandName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("<br/>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fotherwise_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f2);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(406,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/sysadm/product/editFavourableActivityUI.jsp(406,6) '${RangeExtList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${RangeExtList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(406,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("rangeExt");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<input type='checkbox' name='actRangeExtIds' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.goodsId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("' checked='checked'/>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rangeExt.goodsName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("<br/>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(447,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/sysadm/product/editFavourableActivityUI.jsp(447,4) '${giftList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${giftList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/sysadm/product/editFavourableActivityUI.jsp(447,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("gift");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<input type='checkbox' name='giftIds' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gift.goodsId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("' checked='checked'/>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gift.goodsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("&nbsp;&nbsp;<input type=\"text\" size=\"10\" value=\"价格:￥");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gift.shopPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"/><br/>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
